version: '3'

services:
  api:
    container_name: share_reader_api
    build: ./api
    volumes: 
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro
    ports:
      - '3000:3000'
    command: npm run dev
    tty: true
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS: ./authentication/share-reader-api-dev.json

  websocket:
    container_name: share_reader_socket
    build: ./socket
    volumes: 
      - ./socket:/usr/src/socket
      - /usr/src/socket/deps  
    ports: 
      - '4000:4000'
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    tty: true
    
  mysql:
    image: mysql
    container_name: share_reader_mysql
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    restart: always
    volumes: 
      - datastore:/var/lib/mysql
      - ./mysql/database:/docker-entrypoint-initdb.d

volumes: 
  datastore:
    driver: local
