FROM elixir:1.12-alpine

RUN mix local.hex --force && \
  mix archive.install hex phx_new 1.5.9 --force && \
  mix local.rebar --force

WORKDIR /usr/src/socket

COPY mix.* .

RUN mix deps.get

COPY . .

RUN mix deps.get